name: publish_release

on:
  release:
    types: [created]
    
jobs:
  release:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
      # build and publish in parallel: linux/386, linux/amd64, linux/arm, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:  
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: darwin
          - goarch: "386"
            goos: darwin
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.17
      with:
        github_token: ${{ secrets.RELEASES_GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.16.4.linux-amd64.tar.gz"
        extra_files: LICENSE README.md

  update-manifest:
    name: Update Scoop Bucket Manifest
    needs: release
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Update manifest using checkver script
        run: |
          git clone https://github.com/lukesampson/scoop.git
          .\scoop\bin\checkver.ps1 tfvm -u -Dir .
      - name: Commit and push manifest
        run: |
          git config --global user.name 'Ethan Hassett'
          git config --global user.email 'ethanhassett@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.RELEASES_GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add tfvm.json
          git commit -m "doc: Update manifest"
          git push origin HEAD:main