name: release

on:
  push:
    tags:
      - "*"

env:
  GO_VERSION: "1.16"

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}

  update-manifest:
    name: Scoop Update
    needs: goreleaser
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Update manifest using checkver script
        run: |
          git clone https://github.com/lukesampson/scoop.git
          .\scoop\bin\checkver.ps1 tfvm -u -Dir .

      - name: Commit and push manifest
        run: |
          git config --global user.name 'Ethan Hassett'
          git config --global user.email 'ethanhassett@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.RELEASER_TOKEN }}@github.com/${{ github.repository }}
          git add tfvm.json
          git commit -m "doc: update manifest"
          git push origin HEAD:master
          