name: Run Go Tests
on:
  push:
    paths:
      - '**.go'
    tags-ignore:
      - '**'
  pull_request:

env:
  GO_VERSION: "1.18"

jobs:
  tests:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run tests
      run: go test ./internal/command
      