name: Update Versions
on:
  pull_request:
    types: [closed]

jobs:
  update-version:
    if: (github.event.pull_request.merged == true) && (github.actor!= 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/github_actions/') == false)
    runs-on: ubuntu-latest
    env:
      HEAD_REF: ${{ github.head_ref }}
    steps:
    - uses: actions/checkout@v3
      name: checkout
      with:
        fetch-depth: 0

    - name: Determine new tag
      id: tag
      run: |
        old_tag=$(git tag --list --sort=-v:refname | grep -v '-' | head -n 1 | sed 's/v//')
        if [[ -z "$old_tag" ]]; then old_tag=0.0.0; fi
        if [[ $HEAD_REF == *"release/"* ]]
        then
          new_tag=`echo $old_tag | awk -F. '{print "v"$1+1".0.0"}'`
        elif [[ $HEAD_REF == *"feat/"* ]]
        then
          new_tag=`echo $old_tag | awk -F. '{print "v"$1"."$2+1".0"}'`
        elif [[ $HEAD_REF == *"fix/"* ]]
        then
          new_tag=`echo $old_tag | awk -F. '{print "v"$1"."$2"."$3+1}'`
        else
          exit 1
        fi
        echo "::set-output name=tag::$new_tag"

    - name: Update main.go version
      env:
        NEW_TAG: ${{ steps.tag.outputs.tag }}
      run: |
        old_tag=`git describe --tags --abbrev=0 | sed 's/v//'`
        sed -i '' s/$old/$NEW_TAG/g main.go

    - name: Commit and push version changes
      uses: actions-js/push@v1.3
      with:
        github_token: ${{ secrets.RELEASER_TOKEN }}
        message: "chore: update version"
        branch: master

    - name: Push tag
      env:
        NEW_TAG: ${{ steps.tag.outputs.tag }}
      run: |
        git tag $NEW_TAG
        git push --tags
